Restored check with latest version
bazelbuild/rules_scala pull request #1205
Opened 2021-02-03 11:35 UTC by or-shachar

### Description
In travis we used to have a non-failing test_rules_scala that checked if tests passs when working with latest bazel version

I wish to restore it.

IIUC - this would do exactly the same thing - adding buildkite warn annotation in case the step using the latest version fails.

2021-02-03 14:54 UTC, liucijus requested changes
Great feature! Can the message be tuned a bit to not scare users who are not aware what this test is about? Something like:
`Non mandatory build with the latest Bazel version failed` (please improve the wording).

2021-02-24 07:25 UTC, liucijus commented
@or-shachar ping

2021-04-07 17:19 UTC, liucijus approved these changes

2021-04-09 04:29 UTC, ittaiz approved these changes

2021-04-09 05:09 UTC, merged