Jacoco failure targets
bazelbuild/rules_scala pull request #1252
Opened 2021-03-19 11:08 UTC by jauniusb

### Description
Partially url-encode '=' in file names before providing them to JacocoInstrumenter .

Currently files provided as arguments for JacocoInstrumenter are separated by '='. That leads to problems if files or target names contain '=' in names.  PR suggests naive approach to encoding - partially encode (just % and = symbols) using url encoder. Decoder is already available in JVM and easy to implement in skylark side without introducing external libs for encoding.

### Motivation
Currently `bazel coverage` cannot be run on targets where names include '=' sign.

2021-03-25 07:46 UTC, liucijus approved these changes

2021-03-25 08:48 UTC, simuons requested changes
Does [records lists](https://github.com/bazelbuild/rules_scala/pull/1252/files#diff-2b3f817502c3760ada7c2d9d57028527b246c07823e4b60678b60939583be7b8R40) ever gets a size other than one? I think it's always a list of single element.

To me the need of some encoding scheme indicates an issue with args format.

I'd suggest to change args format as follows

```starlark
input_jar = ctx.outputs.jar
output_jar = ctx.actions.declare_file(
    "{}-offline.jar".format(input_jar.basename.split(".")[0]),
)

args = ctx.actions.args()
args.set_param_file_format("multiline")
args.use_param_file("@%s", use_always = True)
args.add(input_jar)
args.add(output_jar)
args.add_all(ctx.files.srcs)

ctx.actions.run(
    mnemonic = "JacocoInstrumenter",
    inputs = [input_jar],
    outputs = [output_jar],
    executable = ctx.attr._code_coverage_instrumentation_worker.files_to_run,
    execution_requirements = {"supports-workers": "1"},
    arguments = [args],
)

replacements = {input_jar: output_jar}
```

and on worker side parse them as follows
```java
Path inPath = Paths.get(args[0]);
Path outPath = Paths.get(args[1]);
String[] srcs = Arrays.copyOfRange(args, 2, args.length);
....
Path pathsForCoverage = instrumentedClassesDirectory.resolve("-paths-for-coverage.txt");
Files.write(
    pathsForCoverage,
    String.join("\n", srcs).getBytes(java.nio.charset.StandardCharsets.UTF_8)
);
```

To be honest I don't know history and motivation why jacoco worker accepts current "records" format. Looking at the code I understand that it always instruments single target at a time. 

Maybe @ittaiz has more insights?

2021-03-25 18:29 UTC, ittaiz commented
I don't remember, sorry...

2021-04-09 05:58 UTC, simuons approved these changes

2021-04-11 06:02 UTC, liucijus approved these changes

2021-04-11 07:33 UTC, ittaiz approved these changes

2021-04-30 04:14 UTC, simuons commented
@ittaiz could you please merge this one

2021-04-30 04:21 UTC, ittaiz commented
@simuons following https://github.com/bazelbuild/rules_scala/pull/1263 🥳  you can merge it yourself.
Give it a try.

2021-05-04 08:03 UTC, merged