Justinass/dep analyzer 3
bazelbuild/rules_scala pull request #1395
Opened 2022-05-17 14:16 UTC by justinass-wix

### Description

### Motivation

2022-05-18 11:55 UTC, liucijus commented on third_party/dependency_analyzer/src/test/io/bazel/rulesscala/dependencyanalyzer3/UnusedDependencyCheckerTest.scala
> +  ignore("do not error on used direct dependencies") {
Why is this test ignored? If it can't be fixed now, it would be very useful to have explanatory comment

2022-05-18 12:14 UTC, liucijus requested changes
Thanks for taking this, @justinass-wix!

Some requests from my side:
- this PR adds Scala 3 specific implementation, but does not fully finish the analyzer feature. Could you add documentation for what is missing? Can be a code comment, or a readme file
- it looks like sources for classes like `OptionParser` are duplicated between version specific packages, can they be extracted to a separate package to minimize the differences between version specific implementations?

2022-05-27 12:53 UTC, liucijus approved these changes

2022-06-10 06:10 UTC, justinass-wix commented
@liucijus can you merge it, or is there something missing?

2022-06-10 06:43 UTC, liucijus commented
> @liucijus can you merge it, or is there something missing?

@simuons we need your review

2022-06-10 07:12 UTC, simuons requested changes
Hi @justinass-wix, thanks for PR and sorry for delay.

I did quick look over the changes (have limited capacity these days) and left few comments. Overall looks good.

2022-06-10 07:12 UTC, simuons commented on third_party/dependency_analyzer/src/main/io/bazel/rulesscala/dependencyanalyzer3/DependencyAnalyzerSettings.scala
> +      optionsParser
Default are a bit confusing. If unsupported value is passed then it default to `error` if no value defaults to `off`. Maybe default should be off all other values should fail.

2022-06-10 07:12 UTC, simuons commented on third_party/utils/src/test/io/bazel/rulesscala/utils/Scala3CompilerUtils.scala
> +  sealed trait CompileResult {
This looks a bit suspicious. You have an ADT to represent success and failure and also have a boolean field for same purpose. Could `isSuccess` be removed?

2022-06-10 07:12 UTC, simuons commented on third_party/utils/src/test/io/bazel/rulesscala/utils/Scala3CompilerUtils.scala
> +  object DependencyTrackingMethod {
Isn't this duplicated with production code?

2023-05-10 07:03 UTC, closed without merging