For Windows: Fix to enable scala_test and scala_binary outputs to be executed on Windows
bazelbuild/rules_scala pull request #1502
Opened 2023-06-23 05:54 UTC by crt-31

### Description
For Windows, this PR fixes issue where outputs of scala_test and scala_binary are failing when ran with 'bazel run' and 'bazel test'. When trying to do run or test, Bazel shows error like:

> LAUNCHER ERROR: rlocation failed on “external\localjdk\bin\java.exe not found in MANIFEST”.

The Fix:  On Windows, Bazel’s Java Launcher was being passed paths in the wrong ‘form’. The launcher expects rpathlocation form for some paths and rootpath form for others. Fix is to pass the right forms of the paths to the LauncherFileWriter which in turn passes correct paths into the Launcher.

### Motivation
scala_test and scala_binary should work properly on Windows

Seems to have been caused by #1313
Should also fix #1497

#### Test/Reproduction
The following can be used as a demonstration test on windows (will fail before this PR):

`bazel test //test/RunScalaBinary --enable_runfiles --extra_toolchains=//scala:minimal_direct_source_deps`

Note that: 'bazel test' requires --enable_runfiles to be set on Windows. 
Also note that many other tests fail in Windows, but fixes for those are for a separate PR.

2023-06-26 18:03 UTC, liucijus requested changes
Thanks, @crt-31! LGTM (assuming I have no Windows environment to test), please address the nits.

2023-06-27 23:23 UTC, crt-31 commented on scala/private/common.bzl
> +    p = paths.normalize(ctx.workspace_name + "/" + rootpath)
done.

2023-06-27 23:23 UTC, crt-31 commented on scala/private/phases/phase_write_executable.bzl
> +    specifiedEnv = {}
done

2023-06-30 05:29 UTC, liucijus approved these changes

2023-07-03 07:01 UTC, simuons approved these changes

2023-07-03 07:01 UTC, merged