Change SemanticdbInfo.plugin_jar from string to File
bazelbuild/rules_scala pull request #1530
Opened 2023-12-01 00:43 UTC by crt-31

### Description
Changed SemanticdbInfo.plugin_jar from path string to File

### Motivation
This keeps the File object available for users of SemanticdbInfo. 

Addresses #1527 

(Note, this does change the public interface a bit, but should be fine since SemanicDBInfo is very new.)

2023-12-04 06:20 UTC, liucijus requested changes
Thanks, @crt-31! Please fix build failures, otherwise LGTM

2023-12-04 23:03 UTC, crt-31 commented
build failure has been fixed.

2023-12-06 06:48 UTC, liucijus approved these changes

2023-12-19 09:25 UTC, simuons approved these changes

2023-12-19 09:25 UTC, merged