Fix to close the compiler object in scalacinvoker
bazelbuild/rules_scala pull request #1545
Opened 2024-02-12 20:55 UTC by crt-31

### Description
This fixes functionality that was accidently broken in PR #1529   (my bad).

The fix is to call close on the compiler within the scalaCWorker (originally added in PR #1504)

2024-02-13 07:00 UTC, simuons requested changes
Please fix code formatting. Also wondering maybe same changes needs to be done in `ScalacInvoker3`?

2024-02-17 01:46 UTC, crt-31 commented
@simuons 
> Please fix code formatting. 

Done

> Also wondering maybe same changes needs to be done in `ScalacInvoker3`?

I looked at dotty's sourcecode, and they don't have a close() mechanism like Scala2 does yet.  There is a PR written up for it  https://github.com/lampepfl/dotty/issues/5412.

Suggest we push this PR through, and deal with Scala3 when dotty implements that PR.

2024-02-17 09:27 UTC, liucijus approved these changes

2024-02-19 07:10 UTC, simuons approved these changes

2024-02-19 07:10 UTC, merged