Use version-aware naming for artifact repositories
bazelbuild/rules_scala pull request #1573
Opened 2024-05-08 13:37 UTC by aszady

### Description
It enables the logic implemented in #1562. The choice of toolchains to cover is the same as in #1566.

Now, e.g., instead of referring to the artifact's repository `@io_bazel_rules_scala_scala_compiler`, we need to use the version-aware name, like `@io_bazel_rules_scala_scala_compiler_3_3_0`.

This may require an update in client's code. In particular in cases they don't use the default toolchains provided by the rules, and construct their own dependency providers. One would need to manually add the version suffix to the repository names, or use a construction like `+ version_suffix(SCALA_VERSION)` in their code.

If needed, I can think of two ways for providing backward compatibility:
* not adding the suffix when the version is the default one – adding a bit of complexity to the code :(
* providing some kind of an alias that points from non-suffixed repository to the one with default Scala version

### Motivation
#1290

2024-05-09 07:21 UTC, simuons requested changes
Thanks, @aszady,

Could you please add aliases for backwards compatibility as you proposed
> providing some kind of an alias that points from non-suffixed repository to the one with default Scala version 

Not sure how complicated that would be, but definitely better than adding ifs on default scala version all over the place. Later we could deprecate those aliases and allow people to migrate.

2024-05-09 14:40 UTC, aszady commented
Added. Out of possible solutions, two aliases worked the best for me.
I also tried sth like using `scala_library` with single dependency, though it didn't work well with dependency checker (suggesting unused dependency).
@simuons, please take a look at the revised version.

Now this PR consists of three commits:
1. Preparation: add alias repo for backward compatibility.
2. Do the actual change (this state demonstrates that aliases work).
3. Cleanup: migrate all the internal rules' deps to suffixed repos.

Do you prefer to have them merged together or separately?

2024-05-13 08:05 UTC, simuons approved these changes
Thanks, @aszady

2024-05-13 08:16 UTC, liucijus approved these changes

2024-05-13 08:24 UTC, merged