testing new convention of file
bazelbuild/rules_scala pull request #1608
Opened 2024-09-03 07:37 UTC by lm1nrt

### Description

### Motivation

2024-09-20 11:54 UTC, lm1nrt commented on scripts/create_repository.py
> +  kind_projector_version = "0.13.2" if scala_major < "2.13" else "0.13.3"
Some versions are not compatible/doesn't exist in certain Scala version

2024-09-20 11:56 UTC, lm1nrt commented on scripts/create_repository.py
> +  version = splitted[2] if splitted[2][0].isnumeric() else splitted[3]
The version location in maven coordinates isn't strict, so there are cases that the version is under the x+1 index.

2024-09-20 11:58 UTC, lm1nrt commented on scripts/create_repository.py
> +def get_label(coordinate) -> str:
There are 5 patterns of labels, which are related to the structure of certain group and artifact due to custom naming.

2024-09-20 11:59 UTC, lm1nrt commented on scripts/create_repository.py
> +def get_with_trailing_commas(content) -> str:
After mapping to the dict, there are no trailing commas, so this is a workaround to adjust file to .bzl files / starlark convention and CI-checks failures.

2024-09-20 12:00 UTC, lm1nrt commented on scripts/create_repository.py
> +  if not file.exists():
If file doesn't exist, the script is copying the last file from directory (default sort) and updating it.

2024-09-20 12:02 UTC, lm1nrt commented on scripts/create_repository.py
> +    excluded_artifacts = ["org.scala-lang.modules:scala-parser-combinators_2.11:1.0.4"]
There are artifacts versions that cause CI-check failures after update and exceptions in logs.

2024-09-20 12:02 UTC, lm1nrt commented on scripts/create_repository.py
> +          dependencies = [d for d in deps if d[1:] in labels and "runtime" not in d and "runtime" not in artifact]
Not modifying the runtime dependencies due to CI-checks failure.

2024-09-20 13:24 UTC, lm1nrt commented on scripts/create_repository.py
> +  subprocess.call(f'cs fetch {' '.join(output)} --json-output-file out.json', shell=True)
Creates local file to get the directDependencies for fetched artifacts

2024-09-23 13:56 UTC, lukaszwawrzyk commented
@liucijus @simuons Could you take a look at this PR? It is a first step to improve maven dependency management in rules_scala. It will allow to bump patch versions of scala and add new minor versions faster. Eventually we would like to organize dependencies more, to keep naming consistent, have clear understanding which deps belong into which resolution tree, etc. and have more frequent updates of other dependencies too.

2024-10-17 07:38 UTC, WojciechMazur commented
@liucijus @simuons Ping for taking a look at this PR. 

It adds Scala 3.5.0, while at the same time, we're in the middle of the 3.5.2 release and its artifacts are already available, public release by the end of this week. https://github.com/scala/scala3/issues/21781
The 3.6.0 would be shipped in 5-6 weeks from now. 
Alternatively you could consider merging #1604

As a Scala 3 compiler team, we'd like to help maintain the rules and keep it up to date. The release plan for Scala 3 involves a new stable release every 6-8 weeks. We'd like to include ensuring the new version of compiler would be supported by Bazel scala_rules as part of our release procedure in the similar way as we're dealing currently with other vital parts of Scala tooling (eg. Debug Adapter Protocol, Metals, Scala CLI, Scastie)

Having a tool to easily add new version would be really beneficial here, but we'd also require a bit involvement from the maintainers of Scala rules to ensure changes would be reviewed and merged within a finite time span. I belive that if needed both me and @lukaszwawrzyk would consider getting the maintainer role in this project. If needed we can arrange some discussions on how @virtuslab as organization, can help with development of this project.

2024-10-18 08:13 UTC, simuons requested changes
Thanks, @lm1nrt, that looks good and useful. 
Sorry I made a conflict by merging https://github.com/bazelbuild/rules_scala/pull/1604 first.
 Could you please rebase this PR and I'll merge it once it's green.

2024-10-18 09:17 UTC, simuons approved these changes

2024-10-18 10:26 UTC, lm1nrt commented
@simuons Done :) I thought that these changes caused CI failure: `This could either mean you have to add the '@@rules_java' repository with a statement like `http_archive` in your WORKSPACE file (note that transitive dependencies are not added automatically), or move an existing definition earlier in your WORKSPACE file.`, but AFAIK it seems to be a global problem while looking on other PRs.

2024-10-18 10:31 UTC, simuons commented
@lm1nrt, I'm looking why build is failing. This is not related to your changes. Failing task was supposed to be optional.

2024-10-21 06:26 UTC, simuons commented
Hi, @lm1nrt, I'm really sorry but I'll ask you to rebase once again. Master is green now, so your PR should be as well.

2024-10-21 08:01 UTC, merged