Add Scala 3.6.2 support
bazelbuild/rules_scala pull request #1672
Opened 2024-12-10 16:28 UTC by WojciechMazur

### Description
Adds Scala 3.6.2 support (first stable release of Scala 3.6 series)

### Motivation
https://github.com/scala/scala3/issues/22167

2024-12-10 16:32 UTC, WojciechMazur commented
The only failed CI job (`./test_rules_scala (latest Bazel) on :ubuntu: Ubuntu 20.04 LTS`) is not caused by this PR - it's already present on the main branch 
https://buildkite.com/bazel/rules-scala-scala/builds/5237#0193ade5-855c-4fac-aca2-c4db6afee62b

2024-12-11 18:25 UTC, mbland commented
> The only failed CI job (`./test_rules_scala (latest Bazel) on :ubuntu: Ubuntu 20.04 LTS`) is not caused by this PR - it's already present on the main branch https://buildkite.com/bazel/rules-scala-scala/builds/5237#0193ade5-855c-4fac-aca2-c4db6afee62b

Yup, I've got #1671 out to fix it.

2024-12-16 07:29 UTC, simuons requested changes
Hi, @WojciechMazur,

thanks for PR. Could you please rebase this PR since https://github.com/bazelbuild/rules_scala/pull/1671 was just merged.

Then I'll merge this PR

2024-12-16 09:31 UTC, simuons approved these changes

2024-12-16 09:32 UTC, merged